version: "3.5"

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'

services:
  server:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: liao-server
    command: go run main.go
    restart: always
    ports:
      - '8090:8088'
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    networks:
      network:
        ipv4_address: 177.7.0.12
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.7.33
    container_name: liao-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'laravel' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'Liaoguiming1234!' # root管理员用户密码
    volumes:
      - './docker/data/mysql/conf:/etc/mysql/conf.d'
      - './docker/data/mysql/data:/var/lib/mysql'
      - './docker/.docker-compose/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    networks:
      network:
        ipv4_address: 177.7.0.13
  redis:
    image: redis:6.0.6
    container_name: liao-redis # 容器名
    restart: always
    ports:
      - '6380:6379'
    networks:
      network:
        ipv4_address: 177.7.0.14