version: "2.2"

services:
  server:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    container_name: liao-server
    restart: always
    ports:
      - '8088:8088'
    depends_on:
      - mysql
      - redis
    tty: true

  mysql:
    image: mysql:8.0.21
    container_name: liao-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "13306:3306"  # host物理直接映射端口为13306
    environment:
      MYSQL_DATABASE: 'laravel' # 初始化启动时要创建的数据库的名称
      MYSQL_ROOT_PASSWORD: 'Liaoguiming1234!' # root管理员用户密码
    volumes:
      - '.docker-compose/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'

  redis:
    image: redis:6.0.6
    container_name: liao-redis # 容器名
    restart: always
    ports:
      - '6379:6379'